{
  config,
  lib,
  pkgs,
  inputs,
  ...
}:
{
  imports = [
    ../tweaks/star-citizen.nix
    ../programs/steam.nix
    ../programs/prismlauncher.nix
    ../programs/lutris.nix
    ../programs/r2modman.nix
    ../programs/protonup-qt.nix
    ../programs/gpu-screen-recorder.nix
    ../programs/protontricks.nix
    ../programs/discord.nix
    ../programs/amethyst.nix
  ];
}
