# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "thunderbolt"
    "usbhid"
    "usb_storage"
    "uas"
    "dm_cache"
    "dm_cache_smq"
  ];
  boot.initrd.kernelModules = [
    "dm-snapshot"
    "dm_cache"
    "dm_cache_smq"
  ];
  boot.kernelModules = [
    "kvm-amd"
    "dm_cache"
    "dm_cache_smq"
  ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/root_vg-nixroot";
    fsType = "btrfs";
  };

  fileSystems."/home" = {
    device = "/dev/mapper/root_vg-nixhome";
    fsType = "btrfs";
  };

  fileSystems."/boot" = {
    device = "/dev/nvme0n1p1";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/mnt/bulkgames" = {
    device = "/dev/mapper/bulkgames-games";
    fsType = "btrfs";
    options = [
      "nossd"
      "space_cache=v2"
      "compress=zstd:3"
      "autodefrag"
      "noatime"
      "nofail"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
